spring:
  application:
    name: starto-api
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      url: ${REDIS_URL}

server:
  port: 8081

firebase:
  config-path: ${FIREBASE_CONFIG_PATH}

openai:
  api-key: ${OPENAI_API_KEY}

google:
  ai:
    api-key: ${GEMINI_API_KEY}

razorpay:
  key-id: ${RAZORPAY_KEY_ID}
  key-secret: ${RAZORPAY_KEY_SECRET}
  webhook-secret: ${RAZORPAY_WEBHOOK_SECRET}

stripe:
  api-key: ${STRIPE_API_KEY}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET}

sendgrid:
  api-key: ${SENDGRID_API_KEY}
